"""добавили состояние товара

Revision ID: 7bf1c0cc6afc
Revises: 6a6357ce2f5a
Create Date: 2022-04-26 03:32:01.237939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf1c0cc6afc'
down_revision = '6a6357ce2f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('condition', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'condition')
    # ### end Alembic commands ###
